#!/bin/bash
#PBS -N train_LOGO_NSCC
#PBS -P personal-e1538285
#PBS -q normal
#PBS -l select=1:ncpus=8:ngpus=1:mem=64gb
#PBS -l walltime=02:00:00
#PBS -j oe
#PBS -o train_promID_nscc.log

cd $PBS_O_WORKDIR
source ~/.bashrc
conda activate logo

# 在这里加一个防御性安装，确保万无一失
pip install --no-cache-dir numpy==1.19.5 "protobuf<3.20" matplotlib==3.3.4 scikit-learn==1.0.2 pandas==1.3.5 biopython==1.68

python 01_PromID_trainer.py