#!/bin/bash
#PBS -N logo919_test
#PBS -l select=1:ncpus=8:ngpus=1:mem=64gb
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o /home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/my_repro_04/metrics/logo919_test_upstream99.$PBS_JOBID.log

set -euo pipefail

source ~/miniconda3/etc/profile.d/conda.sh
conda activate logo

cd /home/users/nus/e1538285/scratch/LOGO
export PYTHONPATH=/home/users/nus/e1538285/scratch/LOGO:${PYTHONPATH:-}

nvidia-smi || true

CUDA_VISIBLE_DEVICES=0 python "/home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/1. script/04_LOGO_Chrom_919/02_deep_sea_train_classification_tfrecord.py" \
  --save "/home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/1. script/04_LOGO_Chrom_919" \
  --weight-path "/home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/1. script/04_LOGO_Chrom_919/deepsea_5_gram_2_layer_8_heads_256_dim_990_weights_99-0.982516-0.983271.hdf5" \
  --test-data "/home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/1. script/04_LOGO_Chrom_919/data/deepsea/DeepSEA_data/test_5_gram" \
  --seq-len 990 \
  --we-size 128 \
  --model-dim 256 \
  --transformer-depth 1 \
  --num-heads 8 \
  --batch-size 512 \
  --ngram 5 \
  --stride 1 \
  --num-classes 919 \
  --model-name deepsea_5_gram_2_layer_8_heads_256_dim_990 \
  --steps-per-epoch 4000 \
  --shuffle-size 4000 \
  --use-conv \
  --use-position \
  --class-prediction \
  --verbose 1 \
  --task test