#!/bin/bash
#PBS -N tB_kn_test
#PBS -l select=1:ncpus=8:mem=64gb
#PBS -l walltime=04:00:00
#PBS -q normal
#PBS -j oe
#PBS -o /scratch/users/nus/e1538285/LOGO/03_LOGO_EPI/pbs_logs/tB_make_knowledge_test.log

set -euo pipefail

cd /scratch/users/nus/e1538285/LOGO/03_LOGO_EPI
source ~/miniconda3/etc/profile.d/conda.sh
conda activate logo

echo "START $(date)"
hostname

python -u 03_make_knowledge_npz.py \
  tB test 6 \
  /scratch/users/nus/e1538285/LOGO/data/hg38/GCF_000001405.39_GRCh38.p13_genomic.gff

echo "END $(date)"
