#!/bin/bash
#PBS -N LOGO_Clinvar_919_2002
#PBS -l select=1:ncpus=10:ngpus=1:mem=96GB
#PBS -q normal
#PBS -l walltime=04:00:00
#PBS -j oe
#PBS -o predict_clinvar_919_2002.log

cd "/home/users/nus/e1538285/scratch/LOGO/04_LOGO_Chromatin_Feature/1. script/04_LOGO_Chrom_predict"
source /home/users/nus/e1538285/miniconda3/bin/activate logo
export PYTHONPATH="/home/users/nus/e1538285/scratch/LOGO:$PYTHONPATH"

VCF="/home/users/nus/e1538285/scratch/LOGO/05_LOGO_Variant_Prioritization/1. script/05_LOGO-C2P/Clinvar_C2P/GBERT-C2P/Clinvar_nc_snv_pathogenic_354.vcf"
REF="Genomics/male.hg19.fasta"

mkdir -p fake_background

echo "=== START Clinvar 919 ==="
python GeneBert_predict_vcf_slice_e8-512pos_new.py \
  --inputfile "$VCF" \
  --backgroundfile ./fake_background/ \
  --reffasta "$REF" \
  --maxshift 0 \
  --weight-path ./deepsea_5_gram_2_layer_8_heads_256_dim_weights_128-0.982105-0.983445.hdf5 \
  --seq-len 1000 \
  --model-dim 256 \
  --transformer-depth 2 \
  --num-heads 8 \
  --batch-size 128 \
  --num-classes 919 \
  --shuffle-size 4000 \
  --pool-size 10 \
  --slice-size 5000 \
  --ngram 5 \
  --stride 1

echo "=== START Clinvar 2002 ==="
python GeneBert_predict_vcf_slice_e8.py \
  --inputfile "$VCF" \
  --backgroundfile ./fake_background/ \
  --reffasta "$REF" \
  --maxshift 0 \
  --weight-path ./genebert_5_gram_2_layer_8_heads_256_dim_expecto_[mat]_weights_134-0.9633-0.9671.hdf5 \
  --seq-len 2000 \
  --model-dim 256 \
  --transformer-depth 2 \
  --num-heads 8 \
  --batch-size 128 \
  --num-classes 2002 \
  --shuffle-size 4000 \
  --pool-size 25 \
  --slice-size 5000 \
  --ngram 5 \
  --stride 1

echo "=== DONE Clinvar 919/2002 main prediction ==="
